"""empty message

Revision ID: 283575fa1d8d
Revises: 45560712cfe6
Create Date: 2022-11-29 13:20:02.501989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '283575fa1d8d'
down_revision = '45560712cfe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopping_carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shopping_carts')
    # ### end Alembic commands ###
