"""empty message

Revision ID: 2c6878959ee6
Revises: bdb0e018882b
Create Date: 2022-11-14 13:06:47.603430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c6878959ee6'
down_revision = 'bdb0e018882b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_addresses',
    sa.Column('id', sa.Integer()),
    sa.Column('user_id', sa.Integer()),
    sa.ForeignKeyConstraint(['user_id'], ['addresses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_addresses')
    # ### end Alembic commands ###
